coverage:
  range: 70..100
  round: down
  precision: 1
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
    patch:
      default:
        target: 50%

comment:
  layout: "condensed_header, diff, flags, files"
  require_changes: true

ignore:
  - "tests/**"
  - "docs/**"
