"""Rendering histograms with matplotlib and mplhep."""

from rootfig.plotting.annotations import add_legend, add_stats_box, add_text
from rootfig.plotting.correlation import correlation_figsize, draw_correlation
from rootfig.plotting.figure import (
    AxesLike,
    Layout,
    apply_xbreak,
    break_segments,
    close_figures_since,
    finish_axes,
    make_figure,
    open_figure_ids,
    overlay_artists,
    raise_ylim_above,
    ylabel_for,
)
from rootfig.plotting.hist1d import (
    DATA_STYLE,
    Drawn,
    FlowSpec,
    draw_histograms,
    envelope,
    fold_flow_bins,
    label_flow_bins,
    show_flow_bins,
)
from rootfig.plotting.hist2d import draw_hist2d
from rootfig.plotting.points import draw_efficiencies, draw_profiles
from rootfig.plotting.ratio import draw_ratio_panel, draw_significance_panel, ratio_ylim
from rootfig.plotting.result import Plot, normalize_formats
from rootfig.plotting.style import (
    DARK_THEME,
    DEFAULT_COLORS,
    ROOTFIG_STYLE,
    add_experiment_label,
    align_experiment_label,
    color_cycle,
    dark_theme,
    finalize_figure,
    foreground,
    legend_location,
    resolve_rc,
    style_context,
    use_style,
)

__all__ = [
    "DARK_THEME",
    "DATA_STYLE",
    "DEFAULT_COLORS",
    "ROOTFIG_STYLE",
    "AxesLike",
    "Drawn",
    "FlowSpec",
    "Layout",
    "Plot",
    "add_experiment_label",
    "add_legend",
    "add_stats_box",
    "add_text",
    "align_experiment_label",
    "apply_xbreak",
    "break_segments",
    "close_figures_since",
    "color_cycle",
    "correlation_figsize",
    "dark_theme",
    "draw_correlation",
    "draw_efficiencies",
    "draw_hist2d",
    "draw_histograms",
    "draw_profiles",
    "draw_ratio_panel",
    "draw_significance_panel",
    "envelope",
    "finalize_figure",
    "finish_axes",
    "fold_flow_bins",
    "foreground",
    "label_flow_bins",
    "legend_location",
    "make_figure",
    "normalize_formats",
    "open_figure_ids",
    "overlay_artists",
    "raise_ylim_above",
    "ratio_ylim",
    "resolve_rc",
    "show_flow_bins",
    "style_context",
    "use_style",
    "ylabel_for",
]
